import type { Metadata } from "next"
import "./globals.css"
import { bodyFont } from "@/utils"

export const metadata: Metadata = {
    title: "Daily Dose of CSS",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={bodyFont.className}>
                {children}
            </body>
        </html>
    )
}
